/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizador;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JViewport;
import javax.swing.Timer;
import logica.Dios;
import logica.Escritor;
import logica.Vida;

/**
 *
 * @author Maku
 */
public class FrameTodo extends javax.swing.JFrame implements ActionListener, MouseListener, MouseMotionListener  {
    int gens = 0, tam, arshivo = 0, intentos = 0;  
    int[] regla = new int[4];
    int[][] cargada;
    private Timer timer;
    Color cViva = Color.BLACK, cMuerta = Color.WHITE;
    private Universo un = new Universo();
    Escritor esc = new Escritor();
      
    /**
     * Creates new form FrameTodo
     */
    public FrameTodo() {
        initComponents();    
        timer = new Timer(50, this);
        btnViva.setBackground(cViva);
        btnViva.setContentAreaFilled(false);
        btnViva.setOpaque(true);
        
        btnMuerta.setBackground(cMuerta);
        btnMuerta.setContentAreaFilled(false);
        btnMuerta.setOpaque(true);
    }

    
    public  void pausa(Thread h)
        {
          synchronized(h)
                  {
                      try {
                        h.wait(); // will cause this Thread to block until 
                                          // another thread calls pauseLock.notifyAll()
                                          // Note that calling wait() will 
                                          // relinquish the synchronized lock that this 
                                          // thread holds on pauseLock so another thread
                                          // can acquire the lock to call notifyAll()
                                          // (link with explanation below this code)
                    } catch (InterruptedException ex) {
                       
                    }
                  }
        }
    public void reanuda(Thread h)
        {
            synchronized (h) 
                {            
                    h.notifyAll(); // Unblocks thread
                }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnPausar = new javax.swing.JButton();
        BtnReiniciar = new javax.swing.JButton();
        txtRegla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbGens = new javax.swing.JLabel();
        txtTamUniv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCero = new javax.swing.JButton();
        btnColorCel = new javax.swing.JButton();
        btnColorMuerta = new javax.swing.JButton();
        btnViva = new javax.swing.JButton();
        btnMuerta = new javax.swing.JButton();
        btnFileLoad = new javax.swing.JButton();
        ScrollM = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar análisis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnPausar.setText("Pausar");
        BtnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPausarActionPerformed(evt);
            }
        });

        BtnReiniciar.setText("Reiniciar");
        BtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarActionPerformed(evt);
            }
        });

        txtRegla.setText("2233");
        txtRegla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReglaFocusLost(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Regla");

        lbGens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGens.setText("0 generaciones");

        txtTamUniv.setText("200");
        txtTamUniv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamUnivActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño ");
        jLabel3.setToolTipText("");

        btnCero.setText("Todo cero");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnColorCel.setText("Color celula :3");
        btnColorCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorCelActionPerformed(evt);
            }
        });

        btnColorMuerta.setText("Color celula x.x");
        btnColorMuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorMuertaActionPerformed(evt);
            }
        });

        btnViva.setForeground(new java.awt.Color(255, 255, 255));
        btnViva.setText(":3");
        btnViva.setEnabled(false);

        btnMuerta.setForeground(new java.awt.Color(255, 255, 255));
        btnMuerta.setText("x.x");
        btnMuerta.setEnabled(false);

        btnFileLoad.setText("Cargar Archivo");
        btnFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPausar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegla)
                    .addComponent(btnCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnColorCel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnColorMuerta, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnMuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnFileLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTamUniv))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtRegla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamUniv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(BtnPausar)
                .addGap(18, 18, 18)
                .addComponent(BtnReiniciar)
                .addGap(18, 18, 18)
                .addComponent(btnCero)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorCel)
                    .addComponent(btnViva))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorMuerta)
                    .addComponent(btnMuerta))
                .addGap(18, 18, 18)
                .addComponent(lbGens)
                .addGap(18, 18, 18)
                .addComponent(btnFileLoad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtRegla.getAccessibleContext().setAccessibleName("");

        ScrollM.setAutoscrolls(true);
        ScrollM.setRequestFocusEnabled(false);
        ScrollM.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ScrollMMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollM, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollM, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarActionPerformed
        // TODO add your handling code here:
        //ScrollM.removeAll();
        gens = 0;
        if(autoriza() == 1)
        {
                     ScrollM.revalidate();
                    //   ScrollM.repaint();

                    lbGens.setText("0 generaciones");         
                    tam = Integer.parseInt(txtTamUniv.getText()) ;
                    un = new Universo(regla, tam, cViva, cMuerta);                                                   
                    ScrollM.getViewport().add(un);     
                    ScrollM.setVisible(true);
                    BtnPausar.setText("Pausar"); 
                    timer.stop();      
                    repaint();
        }
    }//GEN-LAST:event_BtnReiniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //INICIAR
        jButton1.setText("Iniciar");                
                if(autoriza() == 1)
                                 {
                                            if(timer.isRunning())
                                                     {
                                                         System.out.println(":3");
                                                     }                  
                                                 else
                                                 {
//                                                     ScrollM.removeAll();
                                                    ScrollM.revalidate(); 
                                                    gens = 0;
                                                    lbGens.setText("0 generaciones");   
                                                    tam = Integer.parseInt(txtTamUniv.getText()) ;
                                                    un = new Universo(regla, tam, cViva, cMuerta);                                                   
                                                   
                                                    ScrollM.getViewport().add(un);     
                                                    ScrollM.setVisible(true);  
                                                     timer.start();
                                                     repaint();
                                                 }
                             }//autoriza
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPausarActionPerformed
        // TODO add your handling code here:
        if(timer.isRunning())
            {
                timer.stop();
                BtnPausar.setText("Reanudar");
            } 
        else
            {
                if(BtnPausar.getText().equals("Reanudar"))
                    {
                        timer.restart();                    
                        BtnPausar.setText("Pausar");
                    }
            }
    }//GEN-LAST:event_BtnPausarActionPerformed

    private void txtTamUnivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamUnivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamUnivActionPerformed

    private void txtReglaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReglaFocusLost
        // TODO add your handling code here:
        setRegla();
        //System.out.println(regla[0]);
    }//GEN-LAST:event_txtReglaFocusLost

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        ScrollM.revalidate();
     //   ScrollM.repaint();
        gens = 0;
        lbGens.setText("0 generaciones");         
        tam = Integer.parseInt(txtTamUniv.getText()) ;
       un = new Universo(regla, tam, 0, cViva, cMuerta);        
        ScrollM.getViewport().add(un);     
        ScrollM.setVisible(true);
        BtnPausar.setText("Reanudar");
        timer.stop();      
        repaint();
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnColorCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorCelActionPerformed
        // TODO add your handling code here:
        JColorChooser ventanaDeColores=new JColorChooser();
        cViva = ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
        btnViva.setBackground(cViva);
        btnViva.setContentAreaFilled(false);
        btnViva.setOpaque(true);
    }//GEN-LAST:event_btnColorCelActionPerformed

    private void btnColorMuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorMuertaActionPerformed
        // TODO add your handling code here:
        JColorChooser ventanaDeColores=new JColorChooser();
        cMuerta = ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
        btnMuerta.setBackground(cMuerta);
        btnMuerta.setContentAreaFilled(false);
        btnMuerta.setOpaque(true);
    }//GEN-LAST:event_btnColorMuertaActionPerformed

    private void ScrollMMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ScrollMMouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_ScrollMMouseWheelMoved

    private void btnFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileLoadActionPerformed
        arshivo = 1;
        JFileChooser f =new JFileChooser();       
        f.showOpenDialog(this);
        File arc =  f.getSelectedFile(); 
       if(arc.getName().substring(arc.getName().lastIndexOf(".")).equals(".txt"))
            {
                        try 
                            {
                                cargada = esc.lee(arc);
                            }
                        catch (IOException ex) 
                            {
                                Logger.getLogger(FrameTodo.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        if(autoriza() == 1)
                            {
                                    ScrollM.revalidate();
                                 //   ScrollM.repaint();
                                    gens = 0;
                                    lbGens.setText("0 generaciones");         
                                    tam = cargada.length;
                                    un = new Universo(regla, tam, cargada, cViva, cMuerta);        
                                    ScrollM.getViewport().add(un);     
                                    ScrollM.setVisible(true);
                                    BtnPausar.setText("Reanudar");
                                    timer.stop();      
                                    repaint();
                            }
            }
       else
       {
           JOptionPane.showMessageDialog(null, "Un .txt >:c");
       }
    }//GEN-LAST:event_btnFileLoadActionPerformed

    public  int[] getRegla()
        {
                   return regla;
        }
    public void setRegla()
        {
            for(int l = 0; l < 4; l++)
                        {
                            regla[l] = Character.getNumericValue(((txtRegla.getText()).charAt(l)));
                        }
        }
    public int getTam()
        {
            return Integer.parseInt(txtTamUniv.getText());
        }
 

    public void setColor()
        {
            //cViva = btnViva.getColor();
        }
public int autoriza()
    {
          if(txtRegla.getText().length() == 4)
                {
                    if(Integer.parseInt(txtTamUniv.getText()) < 10)
                        {
                            JOptionPane.showMessageDialog(null, "Mayor a 10 por favor -3-");
                        }
                    else{
                             if(Integer.parseInt(txtTamUniv.getText()) > 1000)
                                    {
                                        JOptionPane.showMessageDialog(null, "¿Tú quieres que explote, verdad?");
                                    }
                             else
                             {                                             
                                      if(gens > 9) 
                                        {
                                            if(intentos == 0)
                                                {
                                                    JOptionPane.showMessageDialog(null, "Ya se alcanzó el límite de generaciones");
                                                }                                            
                                            if(intentos == 1)
                                                {
                                                    JOptionPane.showMessageDialog(null, "No");
                                                }
                                            if(intentos == 2)
                                                {
                                                    JOptionPane.showMessageDialog(null, "¡Que no! >:c");
                                                }
                                             if(intentos == 3)
                                                {
                                                   Usted noAprende = new Usted();
                                                   noAprende.setVisible(true);;
                                                }
                                            if(intentos > 3)
                                                {
                                                    JOptionPane.showMessageDialog(null, "Ya me voy");
                                                    System.exit(0);
                                                }
                                            intentos++;
                                            return 0;
                                        }
                                      else
                                      {
                                          return 1;
                                      }
                             }
                        } 
                }
            else
                {
                    JOptionPane.showMessageDialog(null, "Escribe bien la regla >:c deben ser 4 digitos de la sig forma: '2233'");
                }
          return 0;
    }
    
        public void actionPerformed(ActionEvent e) {
        Object src = e.getSource();  // The object that caused the event.
        if (src == timer) 
            {// Each time the timer fires, a new frame is computed and displayed.
                if(gens > 9)
                    {
                        timer.stop();                        
                    }
                else
                {
                    gens++;                                    
                }
                lbGens.setText(gens + " generaciones");                   
                repaint();        
            }
    
    
    
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new FrameTodo().setVisible(true);               
            }
        });      
    }
    
	public void run() 
                    {
	    
                    }
	private void stopRunning() {
		//toggleRunButton.setText("Start");
				
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPausar;
    private javax.swing.JButton BtnReiniciar;
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane ScrollM;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnColorCel;
    private javax.swing.JButton btnColorMuerta;
    private javax.swing.JButton btnFileLoad;
    private javax.swing.JButton btnMuerta;
    private javax.swing.JButton btnViva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbGens;
    private javax.swing.JTextField txtRegla;
    private javax.swing.JTextField txtTamUniv;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
