/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gol;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JViewport;
import javax.swing.Timer;
import logica.Dios;
import logica.Escritor;
import logica.Vida;

/**
 *
 * @author Maku
 */
public class FrameTodo extends javax.swing.JFrame implements ActionListener, MouseListener, MouseMotionListener  {
    int tiempo = 500, gens = 0, tam, arshivo = 0, zoom = 0;  
    int regla;
    int[] cargada;
    private Timer timer;
    Color cViva = Color.BLACK, cMuerta = Color.WHITE;
    private Universo un = new Universo();
    Escritor esc = new Escritor();
      
    /**
     * Creates new form FrameTodo
     */
    public FrameTodo() {
        initComponents();    
        timer = new Timer(50, this);
        btnViva.setBackground(cViva);
        btnViva.setContentAreaFilled(false);
        btnViva.setOpaque(true);
        
        btnMuerta.setBackground(cMuerta);
        btnMuerta.setContentAreaFilled(false);
        btnMuerta.setOpaque(true);
    }

    
    public  void pausa(Thread h)
        {
          synchronized(h)
                  {
                      try {
                        h.wait(); // will cause this Thread to block until 
                                          // another thread calls pauseLock.notifyAll()
                                          // Note that calling wait() will 
                                          // relinquish the synchronized lock that this 
                                          // thread holds on pauseLock so another thread
                                          // can acquire the lock to call notifyAll()
                                          // (link with explanation below this code)
                    } catch (InterruptedException ex) {
                       
                    }
                  }
        }
    public void reanuda(Thread h)
        {
            synchronized (h) 
                {            
                    h.notifyAll(); // Unblocks thread
                }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnPausar = new javax.swing.JButton();
        BtnStep = new javax.swing.JButton();
        BtnReiniciar = new javax.swing.JButton();
        txtRegla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        VelocidadSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        lbGens = new javax.swing.JLabel();
        txtTamUniv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCero = new javax.swing.JButton();
        btnColorCel = new javax.swing.JButton();
        btnColorMuerta = new javax.swing.JButton();
        btnViva = new javax.swing.JButton();
        btnMuerta = new javax.swing.JButton();
        btnFileLoad = new javax.swing.JButton();
        btnGuardaMatriz = new javax.swing.JButton();
        Zoom = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabelZoom = new javax.swing.JLabel();
        ScrollM = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnPausar.setText("Pausar");
        BtnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPausarActionPerformed(evt);
            }
        });

        BtnStep.setText(">");
        BtnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStepActionPerformed(evt);
            }
        });

        BtnReiniciar.setText("Reiniciar");
        BtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarActionPerformed(evt);
            }
        });

        txtRegla.setText("0");
        txtRegla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReglaFocusLost(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Regla");

        VelocidadSlider.setMaximum(50);
        VelocidadSlider.setMinimum(1);
        VelocidadSlider.setPaintLabels(true);
        VelocidadSlider.setToolTipText("");
        VelocidadSlider.setValue(5);
        VelocidadSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VelocidadSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                VelocidadSliderStateChanged(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Velocidad de generación");

        jLabelTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTiempo.setText("segundos");

        lbGens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGens.setText("0 generaciones");

        txtTamUniv.setText("200");
        txtTamUniv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamUnivActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño ");
        jLabel3.setToolTipText("");

        btnCero.setText("Todo cero");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnColorCel.setText("Color celula :3");
        btnColorCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorCelActionPerformed(evt);
            }
        });

        btnColorMuerta.setText("Color celula x.x");
        btnColorMuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorMuertaActionPerformed(evt);
            }
        });

        btnViva.setForeground(new java.awt.Color(255, 255, 255));
        btnViva.setText(":3");
        btnViva.setEnabled(false);

        btnMuerta.setForeground(new java.awt.Color(255, 255, 255));
        btnMuerta.setText("x.x");
        btnMuerta.setEnabled(false);

        btnFileLoad.setText("Cargar Archivo");
        btnFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileLoadActionPerformed(evt);
            }
        });

        btnGuardaMatriz.setText("Guardar");
        btnGuardaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaMatrizActionPerformed(evt);
            }
        });

        Zoom.setMaximum(10);
        Zoom.setMinimum(-5);
        Zoom.setValue(0);
        Zoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ZoomStateChanged(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Zoom");

        jLabelZoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZoom.setText("1x");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbGens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPausar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnStep, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnReiniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegla, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VelocidadSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTiempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTamUniv))
                            .addComponent(btnCero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnColorCel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnColorMuerta, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMuerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnFileLoad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardaMatriz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Zoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtRegla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamUniv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnStep))
                .addGap(18, 18, 18)
                .addComponent(BtnPausar)
                .addGap(18, 18, 18)
                .addComponent(BtnReiniciar)
                .addGap(18, 18, 18)
                .addComponent(btnCero)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorCel)
                    .addComponent(btnViva))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorMuerta)
                    .addComponent(btnMuerta))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(VelocidadSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTiempo)
                .addGap(18, 18, 18)
                .addComponent(lbGens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFileLoad)
                .addGap(18, 18, 18)
                .addComponent(btnGuardaMatriz)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Zoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelZoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtRegla.getAccessibleContext().setAccessibleName("");
        VelocidadSlider.getAccessibleContext().setAccessibleName("Velocidad");

        ScrollM.setAutoscrolls(true);
        ScrollM.setRequestFocusEnabled(false);
        ScrollM.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ScrollMMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollM, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollM, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStepActionPerformed
        // TODO add your handling code here:
        if(autoriza() == 1)
                {                                   
                        if(gens == 0 && arshivo == 0)
                         {
                             ScrollM.revalidate(); 
                             tam = Integer.parseInt(txtTamUniv.getText()) ;
                             un = new Universo(regla, tam,getTiempo(), cViva, cMuerta);                                                   
                             ScrollM.getViewport().add(un);     
                             ScrollM.setVisible(true);                                                   
                             repaint();
                             gens++;
                         }
                        else
                         {
                             arshivo = 0;
                             repaint();
                             gens++;
                         }                        
                        un.setTiempo(tiempo);
                        un.setZoom(zoom);
                        lbGens.setText(gens + " generaciones");
                        BtnPausar.setText("Reanudar");
                            
                }
 
    }//GEN-LAST:event_BtnStepActionPerformed

    private void BtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarActionPerformed
        // TODO add your handling code here:
        //ScrollM.removeAll();
        if(autoriza() == 1)
        {
                     ScrollM.revalidate();
                    //   ScrollM.repaint();
                    gens = 0;
                    lbGens.setText("0 generaciones");         
                    tam = Integer.parseInt(txtTamUniv.getText()) ;
                    un = new Universo(regla, tam,getTiempo(), cViva, cMuerta);                                                   
                    ScrollM.getViewport().add(un);     
                    ScrollM.setVisible(true);
                    BtnPausar.setText("Pausar"); 
                    timer.stop();      
                    repaint();
                    un.setTiempo(tiempo);
                    un.setZoom(zoom);
        }
    }//GEN-LAST:event_BtnReiniciarActionPerformed

    private void VelocidadSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_VelocidadSliderStateChanged
        // TODO add your handling code here:
        
        jLabelTiempo.setText(Float.toString((float) (1.0 / VelocidadSlider.getValue())) + " segundos");    
        tiempo = 1000/VelocidadSlider.getValue();
        setTiempo(tiempo);        
    }//GEN-LAST:event_VelocidadSliderStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //INICIAR
        jButton1.setText("Iniciar");                
                if(autoriza() == 1)
                                 {
                                            if(timer.isRunning())
                                                     {
                                                         System.out.println(":3");
                                                     }                  
                                                 else
                                                 {
//                                                     ScrollM.removeAll();
                                                    ScrollM.revalidate(); 
                                                    gens = 0;
                                                    lbGens.setText("0 generaciones");   
                                                    tam = Integer.parseInt(txtTamUniv.getText()) ;
                                                    un = new Universo(regla, tam,getTiempo(), cViva, cMuerta);                                                   
                                                   
                                                    ScrollM.getViewport().add(un);     
                                                    ScrollM.setVisible(true);  
                                                     timer.start();
                                                     repaint();
                                                 }
                             }//autoriza
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPausarActionPerformed
        // TODO add your handling code here:
        if(timer.isRunning())
            {
                timer.stop();
                BtnPausar.setText("Reanudar");
            } 
        else
            {
                if(BtnPausar.getText().equals("Reanudar"))
                    {
                        timer.restart();                    
                        
                        BtnPausar.setText("Pausar");
                    }
            }        
    }//GEN-LAST:event_BtnPausarActionPerformed

    private void txtTamUnivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamUnivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamUnivActionPerformed

    private void txtReglaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReglaFocusLost
        // TODO add your handling code here:
        setRegla();
        //System.out.println(regla[0]);
    }//GEN-LAST:event_txtReglaFocusLost

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        ScrollM.revalidate();
     //   ScrollM.repaint();
        gens = 0;
        lbGens.setText("0 generaciones");         
        tam = Integer.parseInt(txtTamUniv.getText()) ;
       un = new Universo(regla, tam, getTiempo(),0, cViva, cMuerta);        
        ScrollM.getViewport().add(un);     
        ScrollM.setVisible(true);
        BtnPausar.setText("Reanudar");
        timer.stop();      
        repaint();
        un.setTiempo(tiempo);
        un.setZoom(zoom);        
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnColorCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorCelActionPerformed
        // TODO add your handling code here:
        JColorChooser ventanaDeColores=new JColorChooser();
        cViva = ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
        btnViva.setBackground(cViva);
        btnViva.setContentAreaFilled(false);
        btnViva.setOpaque(true);
    }//GEN-LAST:event_btnColorCelActionPerformed

    private void btnColorMuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorMuertaActionPerformed
        // TODO add your handling code here:
        JColorChooser ventanaDeColores=new JColorChooser();
        cMuerta = ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
        btnMuerta.setBackground(cMuerta);
        btnMuerta.setContentAreaFilled(false);
        btnMuerta.setOpaque(true);
    }//GEN-LAST:event_btnColorMuertaActionPerformed

    private void ScrollMMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ScrollMMouseWheelMoved
        // TODO add your handling code here:
        Dimension d = ScrollM.getViewport().getSize();
       if(evt.getPreciseWheelRotation() > 0)
        {
           d.height /= 1.5;
           d.width /= 1.5;
        }
       else
        {
           d.height *= 1.5;
           d.width *= 1.5;
        }
       //JViewport m = ScrollM.getViewport();
       Component[] a;
       //a = ScrollM.getComponents();
       a = ScrollM.getViewport().getComponents();
       //m.setSize(d);
       if(d.height > 500 && d.width > 500 && a[0] instanceof JPanel)
       {     
            a[0].setSize(d);
            //ScrollM.removeAll();
       //ScrollM.setViewport(m);
            ScrollM.getViewport().add(a[0]);
           //ScrollM.revalidate();
            System.out.println(d.width + "" + d.height + " ");
            repaint();
       }
    }//GEN-LAST:event_ScrollMMouseWheelMoved

    private void btnGuardaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaMatrizActionPerformed
        // TODO add your handling code here:
        int w[];
        w = un.getMatriz();
        if(esc.escribe(w) == 1)
            {
                JOptionPane.showMessageDialog(null, "Se ha creado un sensual archivo");
            }
        else
            {
                JOptionPane.showMessageDialog(null, "No se pudo crear el archivo ;3;");
            }

        

    }//GEN-LAST:event_btnGuardaMatrizActionPerformed

    private void btnFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileLoadActionPerformed
        arshivo = 1;
        JFileChooser f =new JFileChooser();       
        f.showOpenDialog(this);
        File arc =  f.getSelectedFile(); 
         if(arc.getName().substring(arc.getName().lastIndexOf(".")).equals(".txt"))
            {
                        try 
                            {
                                cargada = esc.lee(arc);
                                for(int i = 0; i < cargada.length; i++)
                                    System.out.print("-"+cargada[i]);
                            }
                        catch (Exception ex) 
                            {
                                Logger.getLogger(FrameTodo.class.getName()).log(Level.SEVERE, null, ex);                             
                            }
                        if(autoriza() == 1)
                            {
                                    ScrollM.revalidate();
                                 //   ScrollM.repaint();
                                    gens = 0;
                                    lbGens.setText("0 generaciones");         
                                    tam = cargada.length;                                          
                                    un = new Universo(regla, tam, getTiempo(),cargada, cViva, cMuerta);        
                                    ScrollM.getViewport().add(un);     
                                    ScrollM.setVisible(true);
                                    BtnPausar.setText("Reanudar");
                                    timer.stop();      
                                    repaint();
                            }
            }
       else
       {
           JOptionPane.showMessageDialog(null, "Un .txt >:c");
       }
    }//GEN-LAST:event_btnFileLoadActionPerformed

    private void ZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ZoomStateChanged
        // TODO add your handling code here:
        jLabelZoom.setText(Float.toString((float) (Zoom.getValue())) + "x");    
        zoom = Zoom.getValue();
        setZoom(zoom);     
    }//GEN-LAST:event_ZoomStateChanged

    public  int getRegla()
        {
                   return regla;
        }
    public void setRegla()
        {
            regla = Integer.parseInt(txtRegla.getText());                      
        }
    public int getTam()
        {
            return Integer.parseInt(txtTamUniv.getText());
        }
    public void setTiempo(int tiempo)
        {
            this.tiempo = tiempo;
        }
    public int getTiempo()
        {
            return tiempo;
        }
    public void setZoom(int zoom)
        {
            this.zoom = zoom;
        }
    public int getZoom()
        {
            return zoom;
        }    
    public void setColor()
        {
            //cViva = btnViva.getColor();
        }
public int autoriza()
    {
          if(Integer.parseInt(txtRegla.getText()) >=  0 && Integer.parseInt(txtRegla.getText()) <=  256)
                {
                    if(Integer.parseInt(txtTamUniv.getText()) < 10)
                        {
                            JOptionPane.showMessageDialog(null, "Mayor a 10 por favor -3-");
                        }
                    else{
                             if(Integer.parseInt(txtTamUniv.getText()) > 1000)
                                    {
                                        JOptionPane.showMessageDialog(null, "¿Tú quieres que explote, verdad?");
                                    }
                             else
                             {                                             
                                       return 1;
                             }
                        } 
                }
            else
                {
                    JOptionPane.showMessageDialog(null, "Escribe bien la regla >:c deben ser [0, 256]'");
                }
          return 0;
    }
    
        public void actionPerformed(ActionEvent e) {
        Object src = e.getSource();  // The object that caused the event.
        if (src == timer) 
            {// Each time the timer fires, a new frame is computed and displayed.
                if(gens == tam - 1)
                    {
                        timer.stop();
                    }
                else
                {
                    gens++;
                    un.setTiempo(tiempo);
                    un.setZoom(zoom);
                    lbGens.setText(gens + " generaciones");
                    repaint();
                }
            }
    
    
    
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new FrameTodo().setVisible(true);               
            }
        });      
    }
    
	public void run() 
                    {
	    
                    }
	private void stopRunning() {
		//toggleRunButton.setText("Start");
				
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPausar;
    private javax.swing.JButton BtnReiniciar;
    private javax.swing.JButton BtnStep;
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane ScrollM;
    private javax.swing.JSlider VelocidadSlider;
    private javax.swing.JSlider Zoom;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnColorCel;
    private javax.swing.JButton btnColorMuerta;
    private javax.swing.JButton btnFileLoad;
    private javax.swing.JButton btnGuardaMatriz;
    private javax.swing.JButton btnMuerta;
    private javax.swing.JButton btnViva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelZoom;
    private javax.swing.JLabel lbGens;
    private javax.swing.JTextField txtRegla;
    private javax.swing.JTextField txtTamUniv;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
